-- MySQL Script generated by MySQL Workbench
-- qui 28 ago 2025 11:27:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgcm_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgcm_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgcm_bd` ;
USE `sgcm_bd` ;

-- -----------------------------------------------------
-- Table `sgcm_bd`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`tipo_usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `modulo_administrativo` VARCHAR(1) NOT NULL,
  `modulo_agendamento` VARCHAR(1) NOT NULL,
  `modulo_atendimento` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `senha` VARCHAR(100) NOT NULL,
  `tipo_usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_tipo_usuario_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `sgcm_bd`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
