-- MySQL Script generated by MySQL Workbench
-- Wed Nov 26 15:37:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgcm_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgcm_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgcm_bd` ;
USE `sgcm_bd` ;

-- -----------------------------------------------------
-- Table `sgcm_bd`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`tipo_usuario` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `modulo_administrativo` VARCHAR(1) NOT NULL,
  `modulo_agendamento` VARCHAR(1) NOT NULL,
  `modulo_atendimento` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_bd`.`convenios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`convenios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NULL,
  `telefone` VARCHAR(20) NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(50) NULL,
  `nascimento` DATE NULL,
  `cpf` VARCHAR(15) NULL,
  `senha` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(250) NULL,
  `tipo_usuario_id` INT NOT NULL,
  `convenios_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_tipo_usuario_idx` (`tipo_usuario_id` ASC) VISIBLE,
  INDEX `fk_usuarios_convenios1_idx` (`convenios_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `sgcm_bd`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_convenios1`
    FOREIGN KEY (`convenios_id`)
    REFERENCES `sgcm_bd`.`convenios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgcm_bd`.`exames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgcm_bd`.`exames` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `valor` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `sgcm_bd`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_bd`;
INSERT INTO `sgcm_bd`.`tipo_usuario` (`id`, `nome`, `modulo_administrativo`, `modulo_agendamento`, `modulo_atendimento`) VALUES (1024, 'admin', 'S', 'S', 'S');

COMMIT;


-- -----------------------------------------------------
-- Data for table `sgcm_bd`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `sgcm_bd`;
INSERT INTO `sgcm_bd`.`usuarios` (`id`, `nome`, `nascimento`, `cpf`, `senha`, `endereco`, `tipo_usuario_id`, `convenios_id`) VALUES (1024, 'admin', NULL, NULL, 'a35eaf489326af1af19785290e43d963e308248ea427aac32f764214f91d7a1e', NULL, 1024, NULL);

COMMIT;

